---
title: Short Paper
author:
  - name: Anson Main
    email: maina@missouri.edu
    affiliation: School of Natural Resources
    footnote: Corresponding Author
  - name: Elisabeth Webb
    email: webbli@missouri.edu
    affiliation: School of Natural Resources
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
abstract: |
  This is the abstract.

  It consists of two paragraphs.

bibliography: mybibfile.bib
output: rticles::elsevier_article
---

Please find attached the updated meta analysis draft. Also, I have listed the ideas we discussed regarding potential analyses to run. See below. Basically, these are the variables we would include in each of the models. Some you have already completed. Hopefully there are no issues! Let's aim for a due date of analyses and draft figures/tables by March 11. 


Meta-regression

Behavior/Reproduction and neonic AI (e.g., IMI, CLO) and ppb


Abundance

Seed treatment only and functional group and nesting area

AI type and functional group


Effects on:

Performance measures

Performance measures and functional group

Functional group

Performance measures and nesting area


Behavior

AI type and functional group


Reproduction and order and functional group

Abundance and order and functional group


Behavior and study type

Reproduction and nesting area




_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


The Elsevier article class
==========================

#### Installation

If the document class *elsarticle* is not available on your computer,
you can download and install the system package *texlive-publishers*
(Linux) or install the LaTeX package *elsarticle* using the package
manager of your TeX installation, which is typically TeX Live or MikTeX.

#### Usage

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal. It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
